export enum Order {
  ASC = 'ASC',
  DESC = 'DESC',
}
export enum Comparison {
  EQUAL = 'EQUAL',
  LESS_THAN = 'LESS_THAN',
  LESS_EQUAL_THAN = 'LESS_EQUAL_THAN',
  MORE_THAN = 'MORE_THAN',
  MORE_EQUAL_THAN = 'MORE_EQUAL_THAN',
  NOT = 'NOT',
  LIKE = 'LIKE',
  IN = 'IN',
}
export enum ConnectionNames {
  DB_SASIARAF = 'DB_SASIARAF',
  PRCSIARAF = 'PRCSIARAF',
  DB_SIARAF = 'DB_SIARAF',
  MSSQL_DB_SASIARAF = 'DB_SASIARAF',
  MSSQL_PRCSIARAF = 'PRCSIARAF',
  MSSQL_DB_SIARAF = 'DB_SIARAF',
}
export enum ConnectionEngines {
  MSSQL = 'MSSQL',
  POSTGRES = 'POSTGRES',
}
//nombres de queues de RabbitMQ
export enum RabbitMQ {
  //instrumentos
  instrumentosQueue = 'bitacora.instrumentos',
  BitacoraQueue = 'bitacora',
}
export enum BitacoraMSGs {
  BITACORA_SAVE = 'BITACORA_SAVE',
}
//nombres de mensajes(metodos) de RabbitMQ
export enum CatalogoMSGs {
  ENCOMIENDAS_BMG_FIND_ALL = 'ENCOMIENDAS_BMG_FIND_ALL',
  ENCOMIENDAS_BMG_FIND_ONE = 'ENCOMIENDAS_BMG_FIND_ONE',

  CALENDARIOS_FIND_ALL = 'CALENDARIOS_FIND_ALL',
  CALENDARIOS_FIND_ONE = 'CALENDARIOS_FIND_ONE',
  CALENDARIOS_SAVE = 'CALENDARIOS_SAVE',

  COTIZACION_SCI_FIND_ALL = 'COTIZACION_SCI_FIND_ALL',
  COTIZACION_SCI_FIND_ONE = 'COTIZACION_SCI_FIND_ONE',

  TIPO_AMORTIZACION_SCI_FIND_ALL = 'TIPO_AMORTIZACION_SCI_FIND_ALL',
  TIPO_AMORTIZACION_SCI_FIND_ONE = 'TIPO_AMORTIZACION_SCI_FIND_ONE',

  CLIENTES_FIND_ONE = 'CLIENTES_FIND_ONE',
  CLIENTES_FIND_ALL = 'CLIENTES_FIND_ALL',

  PARAM_FIND_ONE = 'PARAM_FIND_ONE',
  PARAM_FIND_ALL = 'PARAM_FIND_ALL',

  FERIADOS_FIND_ONE = 'FERIADOS_FIND_ONE',
  FERIADOS_FIND_ALL = 'FERIADOS_FIND_ALL',

  TASAS_FIND_ONE = 'TASAS_FIND_ONE',
  TASAS_FIND_ALL = 'TASAS_FIND_ALL',
}
